In [3]:
import sys

# run this cell to install numpy
!{sys.executable} -m pip install numpy

# run this cell to install scipy
!{sys.executable} -m pip install scipy

In [4]:
import numpy as np

# Creating a Basic Array in Numpy
X=np.array([1,2,3,5,5])

In [5]:
# Mean using Numpy
print("Data",X)
print("Mean:",np.mean(X))

Data [1 2 3 5 5]
Mean: 3.2


In [6]:
np.unique(X, return_counts=True)

(array([1, 2, 3, 5]), array([1, 1, 1, 2], dtype=int64))

In [7]:
# Finding Mode using numpy
print("Data",X)
val, count = np.unique(X, return_counts=True)
val, count

Data [1 2 3 5 5]


(array([1, 2, 3, 5]), array([1, 1, 1, 2], dtype=int64))

In [8]:
count

array([1, 1, 1, 2], dtype=int64)

In [9]:
index = np.argmax(count)
print("Index: ", index)
print("Mode numpy:",val[index])

Index:  3
Mode numpy: 5


In [10]:
# Finding Mode using Scipy

from scipy import stats

print("Mode scipy:",stats.mode(X))
modus = stats.mode(X)

Mode scipy: ModeResult(mode=array([5]), count=array([2]))


In [11]:
modus

ModeResult(mode=array([5]), count=array([2]))

In [12]:
# Calculating the Range
print("Data ",X)
print("Range ",X.max()-X.min())

Data  [1 2 3 5 5]
Range  4


In [13]:
# Defining Data
data1=np.array([1, 3, 4, 5, 5, 6, 7, 11])
print("Data",data1)

# First quartile (Q1)
Q1 = np.quantile(data1, .25, interpolation = 'midpoint')
print("\nQuartile 1:",Q1)
 
# Second quartile (Q2)
Q2 = np.quantile(data1, .50, interpolation = 'midpoint')
print("Quartile 2:",Q2)

# Third quartile (Q3)
Q3 = np.quantile(data1, .75, interpolation = 'midpoint')
print("Quartile 3:",Q3)

# Interquaritle range (IQR)
IQR = Q3 - Q1
print("\nInterquartile Range",IQR)

Data [ 1  3  4  5  5  6  7 11]

Quartile 1: 3.5
Quartile 2: 5.0
Quartile 3: 6.5

Interquartile Range 3.0


In [14]:
print("Data",data1)
percentile_20 = np.percentile(data1,20)
print("20th Percentile:",round(percentile_20,2))

Data [ 1  3  4  5  5  6  7 11]
20th Percentile: 3.4


In [15]:
import numpy as np

data1=np.array([1, 3, 4, 5, 5, 6, 7, 11])

print("Data",data1)

'''
    "Delta Degrees of Freedom": the divisor used in the calculation is
    ``N - ddof``, where ``N`` represents the number of elements. By
    default `ddof` is zero.
'''
print("Varaince:",np.var(data1,ddof=1))
print("Standard Deviation:",np.std(data1,ddof=0)) # populasi
print("Standard Deviation:",np.std(data1,ddof=1)) # sampel

Data [ 1  3  4  5  5  6  7 11]
Varaince: 8.785714285714286
Standard Deviation: 2.7726341266023544
Standard Deviation: 2.9640705601780613


In [16]:
import numpy as np
import statistics

E = [60,70,70,70,80,80,80,80,90,100]
F = [75,75,75,75,80,80,80,80,80,80]

# mean
print("Nilai Mean E : ", np.mean(E))

# range
print("Nilai Range E :", np.max(E) - np.min(E))

# varians
print("Nilai Varians E :", np.var(E))

# Standart Deviasi
print("Nilai Standart Deviasi E: ", np.std(E)) # std populasi
print("Nilai Standart Deviasi E: ", statistics.stdev(E)) # std sampel, bisa pakai pst.dev untuk populasi

Nilai Mean E :  78.0
Nilai Range E : 40
Nilai Varians E : 116.0
Nilai Standart Deviasi E:  10.770329614269007
Nilai Standart Deviasi E:  11.352924243950934


In [17]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)
y = np.array([9,8,7,6,5,4,3,2,1])
print(y)

print("\nCovariance ",np.cov(x,y)[0,1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]

Covariance  -7.5


In [18]:
# Return a correlation coefficient matrix
print(np.corrcoef(x,y))

[[ 1. -1.]
 [-1.  1.]]


In [19]:
data2=np.linspace(-5,5,100)
print("Kurtosis",stats.kurtosis(data2))

Kurtosis -1.2002400240024003


In [20]:
from IPython.display import HTML
from IPython.display import display

# Taken from https://stackoverflow.com/questions/31517194/how-to-hide-one-specific-cell-input-or-output-in-ipython-notebook
tag = HTML('''<script>
code_show=true; 
function code_toggle() {
    if (code_show){
        $('div.cell.code_cell.rendered.selected div.input').hide();
    } else {
        $('div.cell.code_cell.rendered.selected div.input').show();
    }
    code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
To show/hide this cell's raw code input, click <a href="javascript:code_toggle()">here</a>.''')
display(tag)



from scipy.stats import skewnorm
import matplotlib.pyplot as plt

numValues = 10000
maxValue = 100
skewness = -5   #Negative values are left skewed, positive values are right skewed.

random = skewnorm.rvs(a = skewness,loc=maxValue, size=numValues)  #Skewnorm function

random = random - min(random)      #Shift the set so the minimum value is equal to zero.
random = random / max(random)      #Standadize all the vlues between 0 and 1. 
random = random * maxValue         #Multiply the standardized values by the maximum value.

#Plot histogram to check skewness
plt.hist(random,30,density=True, color = 'red', alpha=0.1)
plt.show()