# TUGAS 8 MARET PAGI


In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

### 1. 2*A

In [11]:
print("Soal : 2*A =")
print (2*A)

Soal : 2*A

[[ 2  4]
 [14 16]]


### 2. 2+A

In [14]:
print("Soal : 2+A =")
print (2+A)

Soal : 2+A =
[[ 3  4]
 [ 9 10]]


### 3. A+B

In [13]:
print("Soal : 2+B =")
print (2+B)

Soal : 2+B =
[[5 7]
 [3 8]]


### 4. A-B

In [12]:
print("Soal : 2+B =")
print (A-B)

Soal : 2+B =
[[-2 -3]
 [ 6  2]]


### 5. Determinan A

In [15]:
print("Determinan Matriks A = ")
print(np.linalg.det(A))

Determinan Matriks A = 
-6.0
